version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: airflow-nginx-proxy
    ports:
      - "8085:8085"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - airflow
    restart: always

networks:
  airflow:
    external: true 